# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpenDataCubeProductLoader
                                 A QGIS plugin
 This plugin visualizes, plot and loads ingested data as raster layer in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-14
        copyright            : (C) 2018 by Ashutosh Vaish
        email                : ashutoshvaish6397@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OpenDataCubeProductLoader class from file OpenDataCubeProductLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .OpenDataCube_Product_Loader import OpenDataCubeProductLoader
    return OpenDataCubeProductLoader(iface)
